AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 900

Resources:
  Function:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Environment:
        Variables:
          CSV_S3_OUTPUT_PREFIX: textract-csv-output
          CSV_S3_OUTPUT_BUCKET: documentsplitterworkflow-textractsimplesyncworkfl-14xa314007k78
          LOG_LEVEL: DEBUG
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.9-v1

